// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYFM0lwzkG9yjy4P3-TYmyGALcM7FCfVY',
    appId: '1:467685700660:web:9c1f598c674b53bd9c8661',
    messagingSenderId: '467685700660',
    projectId: 'kts-app-306a8',
    authDomain: 'kts-app-306a8.firebaseapp.com',
    storageBucket: 'kts-app-306a8.appspot.com',
    measurementId: 'G-1XK1RJPMK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeWtfgJnzLWxMbRj6ncyvEViLILhiItAU',
    appId: '1:467685700660:android:d25af982b21bb4d99c8661',
    messagingSenderId: '467685700660',
    projectId: 'kts-app-306a8',
    storageBucket: 'kts-app-306a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcD98SRuDzUhx1lg10GcO6cdsbyD6k_4s',
    appId: '1:467685700660:ios:483a67125051e27a9c8661',
    messagingSenderId: '467685700660',
    projectId: 'kts-app-306a8',
    storageBucket: 'kts-app-306a8.appspot.com',
    iosBundleId: 'com.shiva.kts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcD98SRuDzUhx1lg10GcO6cdsbyD6k_4s',
    appId: '1:467685700660:ios:a42da61923814af29c8661',
    messagingSenderId: '467685700660',
    projectId: 'kts-app-306a8',
    storageBucket: 'kts-app-306a8.appspot.com',
    iosBundleId: 'com.shiva.kts.RunnerTests',
  );
}
